In [1]:
import numpy as np
from IPython.display import display
import pandas as pd

In [113]:
df=pd.read_csv(r"mobile.csv")
display(df)
#1

def name(n):
    return str(n)[:1]

df['first name']=df['Customer Name'].apply(name)
df

# 2

display(df['Phone Number'].unique())
df['salolar']=df['Phone Number'].str[:3].replace({'053':'Motorola','052':'Cellcom','051':'Golan','050': 'Pelephone'})
df

# 3
#a
display(df['salolar'].value_counts())
#b
display(df['salolar'].unique())
#c
display(df['salolar'].nunique())

# 4 -bonos

# 5
display(df.sort_values(by=['Talked'], ascending=[True]))

display(df.sort_values(by=['Talked','Internet'], ascending=[True,True]))

# 6 
display(df.nlargest( 5 , 'Talked'))
display(df.nsmallest( 3 , 'Internet'))

# 7
display(df['Phone Number'].duplicated())

display(df['Phone Number'].drop_duplicates())

# 8
display(df.sample(3))

      Customer Name Phone Number  Talked  Internet Start Subscription
0   Cynthia Wong MD  050-5380527     231       944         14/09/2022
1         Chad Reed  053-5250617     166       217         28/11/2022
2      James Murphy  051-7292166     483       437         06/04/2021
3         John Dean  054-2952436     435       817         06/01/2021
4      Nancy Bright  052-8402824     208       770         10/10/2022
5      Melinda Ruiz  051-3102790     434       903         23/02/2022
6     Kristin Huber  054-8068151     499       592         18/01/2023
7       Jesus Burke  052-8352627      48       467         19/10/2020
8   Joanna Buchanan  051-3167949     342       919         17/12/2023
9   Christian Lewis  052-3069795     277       740         11/04/2023
10     Amanda Meyer  050-8200916     355       390         03/02/2023
11   Aaron Melendez  050-8270179     553       871         29/01/2023
12    Sierra Morgan  054-6460585     590       614         17/04/2023
13    Timothy Frost  050-5915117     324       429         28/02/2020
14        Keith Lee  052-7653726     256       795         28/10/2022
15   Evelyn Elliott  051-6233404     369       705         17/10/2022
16      Chad Carter  053-9294578      25       350         06/10/2020
17    Matthew Mills  052-7974129     670       571         08/07/2022
18    Jeffrey Hicks  050-8469039     250        99         07/05/2022
19    Janice Palmer  051-8678768     472       105         04/10/2021
20      Diana Scott  051-8932363     134       519         26/04/2021
21      Lacey Henry  051-7222641      58       104         20/06/2023
22    Angela Waters  054-5779698     553       201         19/10/2020
23    Lisa Alvarado  052-1692691     162       389         28/07/2021
24  Jessica Pittman  053-9160566     170       899         23/03/2023
25     Ryan Aguirre  050-4964995     520       372         07/11/2023
26     Alison Moore  050-6467180     105       579         29/11/2020
27     Sarah Martin  051-6973566      24        91         12/04/2023
28  Gregory Stevens  052-7378700      30       858         09/08/2022
29  Jennifer Zavala  053-8258482     591       202         29/06/2020
30     Ryan Aguirre  050-4964995     520       372         07/11/2023
31        John Dean  054-2952436     435       817         06/01/2021
32   Evelyn Elliott  051-6233404     369       705         17/10/2022
33     Alison Moore  050-6467180     105       579         29/11/2020
34  Jessica Pittman  053-9160566     170       899         23/03/2023

array(['050-5380527', '053-5250617', '051-7292166', '054-2952436',
       '052-8402824', '051-3102790', '054-8068151', '052-8352627',
       '051-3167949', '052-3069795', '050-8200916', '050-8270179',
       '054-6460585', '050-5915117', '052-7653726', '051-6233404',
       '053-9294578', '052-7974129', '050-8469039', '051-8678768',
       '051-8932363', '051-7222641', '054-5779698', '052-1692691',
       '053-9160566', '050-4964995', '050-6467180', '051-6973566',
       '052-7378700', '053-8258482'], dtype=object)

salolar
Pelephone    9
Golan        9
Cellcom      7
Motorola     5
054          5
Name: count, dtype: int64

array(['Pelephone', 'Motorola', 'Golan', '054', 'Cellcom'], dtype=object)

5

,Customer Name,Phone Number,Talked,Internet,Start Subscription,first name,salolar
27,Sarah Martin,051-6973566,24,91,12/04/2023,S,Golan
16,Chad Carter,053-9294578,25,350,06/10/2020,C,Motorola
28,Gregory Stevens,052-7378700,30,858,09/08/2022,G,Cellcom
7,Jesus Burke,052-8352627,48,467,19/10/2020,J,Cellcom
21,Lacey Henry,051-7222641,58,104,20/06/2023,L,Golan
26,Alison Moore,050-6467180,105,579,29/11/2020,A,Pelephone
33,Alison Moore,050-6467180,105,579,29/11/2020,A,Pelephone
20,Diana Scott,051-8932363,134,519,26/04/2021,D,Golan
23,Lisa Alvarado,052-1692691,162,389,28/07/2021,L,Cellcom
1,Chad Reed,053-5250617,166,217,28/11/2022,C,Motorola
34,Jessica Pittman,053-9160566,170,899,23/03/2023,J,Motorola
24,Jessica Pittman,053-9160566,170,899,23/03/2023,J,Motorola
4,Nancy Bright,052-8402824,208,770,10/10/2022,N,Cellcom
0,Cynthia Wong MD,050-5380527,231,944,14/09/2022,C,Pelephone
18,Jeffrey Hicks,050-8469039,250,99,07/05/2022,J,Pelephone
14,Keith Lee,052-7653726,256,795,28/10/2022,K,Cellcom
9,Christian Lewis,052-3069795,277,740,11/04/2023,C,Cellcom
13,Timothy Frost,050-5915117,324,429,28/02/2020,T,Pelephone
8,Joanna Buchanan,051-3167949,342,919,17/12/2023,J,Golan
10,Amanda Meyer,050-8200916,355,390,03/02/2023,A,Pelephone
15,Evelyn Elliott,051-6233404,369,705,17/10/2022,E,Golan
32,Evelyn Elliott,051-6233404,369,705,17/10/2022,E,Golan
5,Melinda Ruiz,051-3102790,434,903,23/02/2022,M,Golan
3,John Dean,054-2952436,435,817,06/01/2021,J,054
31,John Dean,054-2952436,435,817,06/01/2021,J,054
19,Janice Palmer,051-8678768,472,105,04/10/2021,J,Golan
2,James Murphy,051-7292166,483,437,06/04/2021,J,Golan
6,Kristin Huber,054-8068151,499,592,18/01/2023,K,054
30,Ryan Aguirre,050-4964995,520,372,07/11/2023,R,Pelephone
25,Ryan Aguirre,050-4964995,520,372,07/11/2023,R,Pelephone
22,Angela Waters,054-5779698,553,201,19/10/2020,A,054
11,Aaron Melendez,050-8270179,553,871,29/01/2023,A,Pelephone
12,Sierra Morgan,054-6460585,590,614,17/04/2023,S,054
29,Jennifer Zavala,053-8258482,591,202,29/06/2020,J,Motorola
17,Matthew Mills,052-7974129,670,571,08/07/2022,M,Cellcom

,Customer Name,Phone Number,Talked,Internet,Start Subscription,first name,salolar
27,Sarah Martin,051-6973566,24,91,12/04/2023,S,Golan
16,Chad Carter,053-9294578,25,350,06/10/2020,C,Motorola
28,Gregory Stevens,052-7378700,30,858,09/08/2022,G,Cellcom
7,Jesus Burke,052-8352627,48,467,19/10/2020,J,Cellcom
21,Lacey Henry,051-7222641,58,104,20/06/2023,L,Golan
26,Alison Moore,050-6467180,105,579,29/11/2020,A,Pelephone
33,Alison Moore,050-6467180,105,579,29/11/2020,A,Pelephone
20,Diana Scott,051-8932363,134,519,26/04/2021,D,Golan
23,Lisa Alvarado,052-1692691,162,389,28/07/2021,L,Cellcom
1,Chad Reed,053-5250617,166,217,28/11/2022,C,Motorola
24,Jessica Pittman,053-9160566,170,899,23/03/2023,J,Motorola
34,Jessica Pittman,053-9160566,170,899,23/03/2023,J,Motorola
4,Nancy Bright,052-8402824,208,770,10/10/2022,N,Cellcom
0,Cynthia Wong MD,050-5380527,231,944,14/09/2022,C,Pelephone
18,Jeffrey Hicks,050-8469039,250,99,07/05/2022,J,Pelephone
14,Keith Lee,052-7653726,256,795,28/10/2022,K,Cellcom
9,Christian Lewis,052-3069795,277,740,11/04/2023,C,Cellcom
13,Timothy Frost,050-5915117,324,429,28/02/2020,T,Pelephone
8,Joanna Buchanan,051-3167949,342,919,17/12/2023,J,Golan
10,Amanda Meyer,050-8200916,355,390,03/02/2023,A,Pelephone
15,Evelyn Elliott,051-6233404,369,705,17/10/2022,E,Golan
32,Evelyn Elliott,051-6233404,369,705,17/10/2022,E,Golan
5,Melinda Ruiz,051-3102790,434,903,23/02/2022,M,Golan
3,John Dean,054-2952436,435,817,06/01/2021,J,054
31,John Dean,054-2952436,435,817,06/01/2021,J,054
19,Janice Palmer,051-8678768,472,105,04/10/2021,J,Golan
2,James Murphy,051-7292166,483,437,06/04/2021,J,Golan
6,Kristin Huber,054-8068151,499,592,18/01/2023,K,054
25,Ryan Aguirre,050-4964995,520,372,07/11/2023,R,Pelephone
30,Ryan Aguirre,050-4964995,520,372,07/11/2023,R,Pelephone
22,Angela Waters,054-5779698,553,201,19/10/2020,A,054
11,Aaron Melendez,050-8270179,553,871,29/01/2023,A,Pelephone
12,Sierra Morgan,054-6460585,590,614,17/04/2023,S,054
29,Jennifer Zavala,053-8258482,591,202,29/06/2020,J,Motorola
17,Matthew Mills,052-7974129,670,571,08/07/2022,M,Cellcom

,Customer Name,Phone Number,Talked,Internet,Start Subscription,first name,salolar
17,Matthew Mills,052-7974129,670,571,08/07/2022,M,Cellcom
29,Jennifer Zavala,053-8258482,591,202,29/06/2020,J,Motorola
12,Sierra Morgan,054-6460585,590,614,17/04/2023,S,054
11,Aaron Melendez,050-8270179,553,871,29/01/2023,A,Pelephone
22,Angela Waters,054-5779698,553,201,19/10/2020,A,054

,Customer Name,Phone Number,Talked,Internet,Start Subscription,first name,salolar
27,Sarah Martin,051-6973566,24,91,12/04/2023,S,Golan
18,Jeffrey Hicks,050-8469039,250,99,07/05/2022,J,Pelephone
21,Lacey Henry,051-7222641,58,104,20/06/2023,L,Golan

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30     True
31     True
32     True
33     True
34     True
Name: Phone Number, dtype: bool

0     050-5380527
1     053-5250617
2     051-7292166
3     054-2952436
4     052-8402824
5     051-3102790
6     054-8068151
7     052-8352627
8     051-3167949
9     052-3069795
10    050-8200916
11    050-8270179
12    054-6460585
13    050-5915117
14    052-7653726
15    051-6233404
16    053-9294578
17    052-7974129
18    050-8469039
19    051-8678768
20    051-8932363
21    051-7222641
22    054-5779698
23    052-1692691
24    053-9160566
25    050-4964995
26    050-6467180
27    051-6973566
28    052-7378700
29    053-8258482
Name: Phone Number, dtype: object

,Customer Name,Phone Number,Talked,Internet,Start Subscription,first name,salolar
6,Kristin Huber,054-8068151,499,592,18/01/2023,K,054
12,Sierra Morgan,054-6460585,590,614,17/04/2023,S,054
1,Chad Reed,053-5250617,166,217,28/11/2022,C,Motorola